kind: Service
apiVersion: v1
metadata:
  name: perclinic-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: petclinic
    